### ISSUE TITLE
Why not directly use LIDAR sensor for obtaining point clouds?

### ISSUE THREAD

**Issue by siddhantkatyan** [iaoqian/carla_3d-mapping_and_adding_virtual_objects#1]

**Comment by kkaiwwana** [comment]
Thank you for your issue. 
The reason is colorized points can not be obtained from LiDAR generated point clouds in Carla.

**Comment by siddhantkatyan** [comment]
Thank you for your reply. The coloring of lidar point cloud can be done by projecting the lidar points onto the camera image and assigning the corresponding color from the image to the lidar points (using intrinsic and extrinsic camera parameters).

**Comment by kkaiwwana** [comment]
Yes, that makes sense and that's in deed more feasible in real word, while they're mostly equivalent in simulator.

Thanks for your issue again. Closing this issue. Feel free to reopen it if you find any necessity.
